### ISSUE TITLE
Migration to 'new' tt-rss gives warnings updating url base from redirection

### ISSUE THREAD

**Issue by jdeluyck** [tt-rss/tt-rss#12]
### What is the problem?

I switched over using the docker images provided by this project (thank you!), and came across these errors:

```
app-1        | updating /var/www/html/tt-rss/plugins.local/nginx_xaccel...
app-1        | fatal: unable to update url base from redirection:
app-1        |   asked for: https://git.tt-rss.org/fox/ttrss-nginx-xaccel.git/info/refs?service=git-upload-pack
app-1        |    redirect: https://github.com/tt-rss/
app-1        | fatal: unable to update url base from redirection:
app-1        |   asked for: https://git.tt-rss.org/fox/ttrss-nginx-xaccel.git/info/refs?service=git-upload-pack
app-1        |    redirect: https://github.com/tt-rss/
app-1        | warning: attempt to update plugin /var/www/html/tt-rss/plugins.local/nginx_xaccel failed.
```

I'm using the docker compose files as they are, without anything fancy (only sticking with PG 17 for now)

### Reproduction Steps

Have the latest version running from tt-rss.org, change the docker images over to the ones from this project.

### tt-rss Version

Tiny Tiny RSS v25.10-2cfb58c

### Environment

Docker

### Acknowledge

(not sure what you mean by this?)

- [ ] I'm interested in implementing the fix

**Comment by supahgreg** [comment]
Ah, yeah this will be an issue for `nginx_accel` and other plugins in `plugins.local` that are git repositories with a remote targeting `git.tt-rss.org` or `gitlab.tt-rss.org`.

Those errors are essentially just noise and unnecessary requests (`nginx_accel` hasn't had a real change in years, similar to many other unbundled plugins that were hosted on `tt-rss.org`), but still something that  should be fixed.

I'll think about this a bit more (maybe special handling of `nginx_xaccel` since it's always present), but in the short-term you could do something like this to switch to the new repository for that plugin:

```bash
# from within your directory with the Docker Compose stuff
docker compose exec --user app app sh

cd ${APP_INSTALL_BASE_DIR}/tt-rss/plugins.local/nginx_xaccel
git remote set-url origin https://github.com/tt-rss/tt-rss-plugin-nginx-xaccel.git
git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
exit
```

Other plugins (meeting the aforementioned criteria) would have a very similar process-- but of course with a different directory name and repo URL.

**Comment by supahgreg** [comment]
I believe this should be addressed by a couple things I've implemented:
1. The `app` startup script will now migrate existing `git.tt-rss.org`- or `gitlab.tt-rss.org`-based plugins over to their equivalent GitHub repo+branch (see #13 and #16)
2. Cloudflare will now redirect `git.tt-rss.org` plugin repo requests over to their GitHub equivalent (which `git` will warn about)

The manual approach mentioned in my prior comment is also an option for anyone that has `TTRSS_NO_STARTUP_PLUGIN_UPDATES` set (or just wants to take that approach).

If anyone runs into issues just let me know.

**Comment by thomas-333** [comment]
I appreciate this is closed but thought it was best here rather than a new ticket.

I have updated my docker image to 2b58774 and I can see from my log that most plugins have been migrated.  However I am still getting an error on two plugins. I note mine are dev.tt-rss.org for some reason?

```
fatal: unable to access 'https://dev.tt-rss.org/tt-rss/ttrss-nginx-xaccel.git/': Could not resolve host: dev.tt-rss.org
fatal: unable to access 'https://dev.tt-rss.org/tt-rss/ttrss-prefs-effective-config.git/': Could not resolve host: dev.tt-rss.org
```

**Comment by supahgreg** [comment]
@thomas-333 Thanks, I'll add handling for `dev.tt-rss.org` (which predates the other subdomains, I believe) in a bit.
